//
//  CourseListInteractor.swift
//  CoursesList
//
//  Created by Kairzhan Kural on 9/24/20.
//  Copyright (c) 2020 Kairzhan Kural. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol CourseListBusinessLogic {
    func fetchCourses(request: CourseList.FetchCourses.Request)
}

protocol CourseListDataStore {
    var courses: [Course] { get }
}

class CourseListInteractor: CourseListBusinessLogic, CourseListDataStore {
    
    var presenter: CourseListPresentationLogic?
    var worker: CourseListWorker?
    var courses: [Course] = []
    
    // MARK: Do something
    
    func fetchCourses(request: CourseList.FetchCourses.Request) {
        worker = CourseListWorker()
        
        NetworkManager.shared.fetchCourses { (courses) in
            self.courses = courses
            let response = CourseList.FetchCourses.Response(courses: courses)
            self.presenter?.presentCourses(response: response)
        }
    }
}
