//
//  CourseListModels.swift
//  CoursesList
//
//  Created by Kairzhan Kural on 9/24/20.
//  Copyright (c) 2020 Kairzhan Kural. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum CourseList {
    // MARK: Use cases
    
    enum FetchCourses {
        struct Request {
        }
        
        struct Response {
            var courses: [Course]
        }
        
        struct ViewModel {
            struct DisplayedCourse {
                var courseName: String?
                var imageData: Data?
            }
            
            var displayedCourses: [DisplayedCourse]
        }
    }
}
