//
//  CourseDetailsModels.swift
//  CoursesList
//
//  Created by Kairzhan Kural on 9/24/20.
//  Copyright (c) 2020 Kairzhan Kural. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum CourseDetails {
    
    // MARK: Use cases
    enum ShowDetails {
        
        struct Request {
        
        }
        
        struct Response {
            let course: Course
            let isFavourite: Bool
        }
        
        struct ViewModel {
            struct DisplayedDetails {
                let courseName: String?
                let numberOfLessons: String?
                let numberOfTests: String?
                let imageData: Data?
                let isFavourite: Bool
            }
            let displayedDetails: DisplayedDetails
        }
    }
    
    enum SetFavouriteStatus {
        
        struct Request {
            
        }
        
        struct Response {
            let isFavourite: Bool
        }
        
        struct ViewModel {
            let isFavourite: Bool
        }
    }
}
