//
//  CourseDetailsWorker.swift
//  CoursesList
//
//  Created by Kairzhan Kural on 9/24/20.
//  Copyright (c) 2020 Kairzhan Kural. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class CourseDetailsWorker {
    
    func fetchImage(from imageUrl: String?) -> Data? {
        return ImageManager.shared.fetchImageData(from: imageUrl)
    }
    
    func getFavouriteStatus(for courseName: String) -> Bool {
        DataManager.shared.loadFavouriteStatus(for: courseName)
    }
    
    func setNewFavouriteStatus(for courseName: String, with status: Bool) {
        DataManager.shared.saveFavouriteStatus(for: courseName, with: status)
    }
}
