//
//  CourseDetailsInteractor.swift
//  CoursesList
//
//  Created by Kairzhan Kural on 9/24/20.
//  Copyright (c) 2020 Kairzhan Kural. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol CourseDetailsBusinessLogic {
    func showDetails(request: CourseDetails.ShowDetails.Request)
    func setFavouriteStatus()
}

protocol CourseDetailsDataStore {
    var course: Course! { get set }
    var isFavourite: Bool { get }
}

class CourseDetailsInteractor: CourseDetailsBusinessLogic, CourseDetailsDataStore {
    
    var presenter: CourseDetailsPresentationLogic?
    var worker: CourseDetailsWorker?
    var course: Course!
    var isFavourite = false
    // MARK: Do something
    
    func showDetails(request: CourseDetails.ShowDetails.Request) {
        worker = CourseDetailsWorker()
        isFavourite = worker?.getFavouriteStatus(for: course.name ?? "") ?? false
        
        let response = CourseDetails.ShowDetails.Response(course: course, isFavourite: isFavourite)
        presenter?.presentDetails(response: response)
    }
    
    func setFavouriteStatus() {
        isFavourite.toggle()
        worker?.setNewFavouriteStatus(for: course.name ?? "", with: isFavourite)
        
        let response = CourseDetails.SetFavouriteStatus.Response(isFavourite: isFavourite)
        presenter?.presentFavouriteStatus(response: response)
    }
}
